### ISSUE TITLE
# Aidl not found, please install it. Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by madDevXD** [digreatbrian/buildozer-action#5]
i got this error when I tried the Action

**Comment by OuchenTech** [comment]
use this in your build.yml:

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: . # directory where your main.py file rests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk

**Comment by OuchenTech** [comment]
> i got this error when I tried the Action

use this in your build.yml:

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: . # directory where your main.py file rests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk

**Comment by OuchenTech** [comment]
> i got this error when I tried the Action
Use this in your build.yml file

```
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: . # directory where your main.py file rests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
```
